#!/usr/bin/python3

# Copyright © 2021 rusty-snake
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

"""
A wrapper around ``rustc`` which replaces ``-C prefer-dynamic`` with ``-C prefer-dynamic=no``.
Workaround for https://github.com/mesonbuild/meson/issues/7576
"""

import subprocess
import sys

try:
    subprocess.run(
        [
            "rustc",
            *(
                arg if arg != "prefer-dynamic" else "prefer-dynamic=no"
                for arg in sys.argv[1:]
            ),
        ],
        check=True,
    )
except subprocess.CalledProcessError as e:
    sys.exit(e.returncode)
